moviestream_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: postgres
      password: postgres
      port: 5432
      dbname: landing_db
      schema: public
      threads: 1
